version: "3.8"

services:
  backend:
    restart: unless-stopped
    image: ghcr.io/corentings/astrocket/backend:v0.3.0
    ports:
      - "8090:8080"
    volumes:
      - ./data:/pb/pb_data
      - ./migrations:/pb/pb_migrations
    networks:
      - app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s
  frontend:
    restart: unless-stopped
    image: ghcr.io/corentings/astrocket/frontend:v0.3.2
    ports:
      - "4321:4321"
    networks:
      - app
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4321 || exit 1
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s


networks:
  app:
    driver: bridge

