version: "3.1"

services:
  app:
    container_name: pocketbase
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    volumes:
      - ./data:/pb/pb_data
      - ./migrations:/pb/pb_migrations
