@startuml C4_Elements

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Uses the application via a Web Browser")
System_Ext(oauthProvider, "OAuth Provider", "External OAuth provider")

System_Boundary(server, "Server") {
    Container(ssrApp, "SSR Application", "Astro") {
            Component(landingPage, "Landing Page", "Static Generated Landing Page")
            Component(assets, "Assets", "Server Side Rendered assets")
    }
    Container(api, "API", "Pocketbase", "Handles requests from the CSR components")
}

System_Boundary(browser, "Browser") {
    Container(csrComponents, "CSR Components", "SolidJS") {
            Component(loginComponent, "Login Component", "Client Side Rendered login component")
            Component(chatRoomComponent, "ChatRoom Component", "Client Side Rendered chat room component")
    }
}

ContainerDb(db, "Database", "Pocketbase", "Stores application data")

Rel(user, browser, "Uses")
Rel(browser, ssrApp, "Interacts with")
Rel(csrComponents, api, "Interacts with")
Rel(api, db, "Uses")
Rel(api, oauthProvider, "Uses for login")

@enduml